AppBundle\Entity\Comment:
  type: entity
  table: comment
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  manyToOne:
    topic:
      cascade: ['persist']
      inversedBy: comments
      joinColumn:
        name: cid
        referencedColumnName: id
      targetEntity: Topic
  fields:
    uid:
      type: integer
    tid:
      type: integer
    pid:
      type: integer
    body:
      type: string
      length: 100
    created:
      type: datetime
    updated:
      type: datetime
    status:
      type: boolean