AppBundle\Entity\Discussion:
  type: entity
  table: discussion
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  oneToOne:
    topic:
      targetEntity: Topic
      mappedBy: discussion
  fields:
    body:
      type: text
    created:
      type: datetime
    updated:
      type: datetime
    status:
      type: boolean
