AppBundle\Entity\Topic:
  type: entity
  table: topic
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  oneToOne:
    discussion:
      cascade: ['persist']
      inversedBy: topic
      joinColumn:
        name: did
        referencedColumnName: id
      targetEntity: Discussion
  fields:
    title:
      type: string
      length: 100
    uid:
      type: integer
    did:
      type: integer
    created:
      type: datetime
    updated:
      type: datetime
    type:
      type: string
      length: 20
    status:
      type: boolean