AppBundle\Entity\User:
  type: entity
  table: user
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 60
    password:
      type: string
      length: 120
    email:
      type: string
      length: 250
    created:
      type: datetime
    updated:
      type: datetime
    status:
      type: boolean